name = "test"
main = "src/index.ts"
send_metrics = false
compatibility_date = "2022-10-12"

[build]
command = "npm run build"

[[services]]
binding = "WORKER"
service = "web-worker-polyfill"
environment = "production"
