name = "test"
main = "src/index.ts"
send_metrics = false
compatibility_date = "2022-07-17"

[build]
command = "npm run build"

[durable_objects]
bindings = [{ name = "WORKER", class_name = "DurableWorker" }]

[[migrations]]
tag = "v1"
new_classes = ["DurableWorker"]
