name = "test"
main = "src/index.ts"
send_metrics = false
compatibility_date = "2022-08-09"

[build]
command = "npm run build"

[[services]]
binding = "WORKER"
service = "web-worker-polyfill"
environment = "production"

# https://github.com/cloudflare/wrangler2/issues/273
[miniflare.mounts]
web-worker-polyfill = "./lib"
